
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[329] =
    {   0,
        0,    0,   95,   93,    2,    2,   84,   93,   77,   93,
       47,   48,   73,   75,   54,   76,   55,   74,   90,   90,
       53,   78,   56,   79,   92,   51,   52,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   49,   93,   50,
       83,    0,   91,   85,   59,   57,   60,   58,   89,   88,
        1,    0,   90,   90,   80,   82,   81,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   36,   92,   92,   92,   92,   92,   16,   92,   92,
       92,   92,   92,   92,   92,   92,   14,   92,   92,   92,

       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   86,    0,    1,   87,   68,   92,
       92,   92,   92,   92,   92,   62,   92,   92,   92,   92,
       92,   92,   92,   92,   17,   92,   92,    3,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       61,   92,   92,   92,   92,   63,   92,   92,   92,   92,
       92,   92,   92,   92,   87,   65,   37,   92,   64,   66,
       92,   39,   92,   92,   18,   19,   92,   40,   92,   92,
       41,   92,   42,   43,   92,   44,   92,   92,   72,   92,
       92,   92,   92,   92,   38,   92,   67,   92,   92,   92,

       92,   92,   21,   92,   45,   46,   92,   92,   92,   92,
       22,   69,   92,   92,   92,   92,   92,   92,   92,   20,
       92,   92,   92,   23,   92,   92,   92,   92,   92,   92,
       92,    8,    4,   92,   92,   92,   92,   92,   92,   92,
        7,   70,   92,   92,   92,    5,   92,   92,   92,   92,
       92,   92,   92,   11,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   10,   71,   92,   26,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
        6,   15,   27,   92,   24,   92,   92,   92,   92,    9,
       92,   92,   92,   92,   92,   92,   35,   34,   25,   92,

       92,   92,   92,   92,   92,   92,   13,   92,   92,   31,
       92,   92,   92,   92,   92,   92,   92,   92,   33,   12,
       28,   92,   32,   92,   92,   30,   29,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       24,    1,   25,    1,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    3,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[333] =
    {   0,
        0,    0,  138, 1431, 1431, 1431,  112,  124, 1431,  117,
     1431, 1431, 1431,   45, 1431,   44,   42,  104,   53,   58,
     1431,   93,   82,   81,   45, 1431, 1431,   61,   64,   67,
       75,   93,   78,  100,  105,  110,  119,  127,  135,  141,
      147,  153,  157,  179,   70,  161,  191, 1431,   46, 1431,
     1431,   92, 1431, 1431, 1431, 1431, 1431, 1431,  169,  195,
        0,  208,  213,  219, 1431, 1431, 1431,    0,  198,  222,
      225,  228,  233,  236,  245,  239,  257,  260,  263,  268,
      271,    0,  276,  280,  283,  287,  291,  299,  302,  309,
      312,  317,  328,  334,  337,  340,  344,  352,  355,  358,

      362,  370,  365,  376,  379,  383,  392,  395,  398,  402,
      405,  412,  415,  427, 1431,  408,    0,  437,  447,  450,
      453,  457,  460,  463,  468,  471,  474,  489,  492,  495,
      498,  502,  505,  511,  517,  520,  523,  532,  537,  541,
      544,  547,  556,  559,  562,  566,  577,  583,  591,  594,
      598,  602,  605,  608,  613,  622,  625,  628,  633,  639,
      642,  651,  654,  659,   48,  662,  665,  669,  672,  675,
      681,  684,  690,  695,  698,  707,  713,  716,  719,  722,
      725,  729,  734,  737,  740,  743,  752,  755,  758,  764,
      767,  771,  776,  779,  782,  788,  791,  798,  804,  812,

      815,  818,  825,  828,  834,  837,  843,  846,  849,  852,
      857,  865,  868,  874,  877,  881,  886,  889,  892,  902,
      907,  910,  913,  919,  925,  931,  937,  943,  946,  949,
      952,  959,  964,  967,  975,  978,  981,  984,  990,  996,
     1001, 1004, 1016, 1020, 1024, 1027, 1030, 1034, 1037, 1042,
     1045, 1050, 1054, 1057, 1061, 1069, 1072, 1081, 1084, 1088,
     1095, 1091, 1098, 1102, 1107, 1114, 1120, 1123, 1126, 1136,
     1139, 1143, 1146, 1151, 1154, 1157, 1162, 1166, 1170, 1178,
     1183, 1186, 1192, 1200, 1203, 1206, 1212, 1217, 1220, 1223,
     1226, 1229, 1236, 1245, 1248, 1251, 1254, 1263, 1267, 1270,

     1276, 1282, 1285, 1288, 1292, 1295, 1303, 1306, 1311, 1315,
     1318, 1321, 1327, 1333, 1336, 1339, 1350, 1354, 1361, 1365,
     1368, 1371, 1377, 1381, 1384, 1388, 1391, 1431, 1424,   65,
     1427,   61
    } ;

static const flex_int16_t yy_def[333] =
    {   0,
      328,    1,  328,  328,  328,  328,  328,  329,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  330,  328,  328,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  328,  328,  328,
      328,  329,  328,  328,  328,  328,  328,  328,  328,  328,
      331,  328,  328,  328,  328,  328,  328,  332,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  332,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  328,  328,  331,  328,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  328,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,    0,  328,  328,
      328,  328
    } ;

static const flex_int16_t yy_nxt[1487] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   21,   22,
       23,   24,   25,   26,   27,   25,   28,   25,   29,   30,
       31,   32,   25,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   25,   42,   43,   44,   45,   25,   46,   25,
       25,   47,   48,   49,   50,   55,   57,   59,   60,   60,
       68,   68,   68,   68,   58,   56,   62,   69,   63,   63,
       63,   62,  165,   63,   64,   64,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   70,   71,
       68,   68,   68,   68,   68,   68,   53,   72,   76,  115,

       73,   67,   66,   78,   77,   74,   75,   79,   68,   82,
       68,  112,   80,   65,   87,   68,   68,   68,   61,   83,
       68,   68,   68,   54,   81,   68,   68,   68,   53,   84,
       85,   88,   51,   86,   68,   68,   68,  328,  328,   89,
      328,   90,   68,   68,   68,  328,   91,  328,  328,   92,
       68,   68,   68,  328,  328,   93,   68,   68,   68,  328,
      328,   94,   68,   68,   68,   96,  328,   95,   68,   68,
       68,  328,   68,   68,   68,  328,   68,   68,   68,  100,
       97,   98,  328,  101,  116,   60,   60,  102,  328,  328,
       99,  103,  328,  104,   68,   68,   68,  113,  105,  106,

      328,  328,  107,  328,  328,  108,   68,   68,   68,  109,
      116,   60,   60,   68,   68,   68,  328,  118,  328,  110,
      328,  328,  111,  118,  118,  118,   62,  114,   63,   63,
       63,  118,   62,  328,   63,   64,   64,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  328,  328,   68,   68,
       68,   68,   68,   68,   68,   68,   68,  328,  121,  328,
       68,   68,   68,  328,  328,  120,  119,  122,  328,  328,
      123,  124,   68,   68,   68,   68,   68,   68,   68,   68,
       68,  328,  125,   68,   68,   68,   68,   68,   68,  328,
      127,   68,   68,   68,  328,   68,   68,   68,   68,   68,

       68,  126,   68,   68,   68,  131,   68,   68,   68,  128,
      133,  129,  130,  132,   68,   68,   68,   68,   68,   68,
      328,  136,  328,  134,   68,   68,   68,   68,   68,   68,
      135,  328,   68,   68,   68,  328,  137,  328,  328,  139,
      328,  328,  140,   68,   68,   68,  328,  138,  141,   68,
       68,   68,   68,   68,   68,   68,   68,   68,  142,   68,
       68,   68,  328,  143,  328,  328,  145,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  328,   68,   68,   68,
       68,   68,   68,  144,  328,   68,   68,   68,  328,  147,
      149,   68,   68,   68,   68,   68,   68,  148,   68,   68,

       68,  146,  150,  328,  151,  153,  152,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  328,   68,   68,   68,
       68,   68,   68,  116,   60,   60,  154,   68,   68,   68,
       68,   68,   68,  328,  156,  155,  328,  328,  162,  160,
      328,  157,   68,   68,   68,  163,  118,  158,  159,  328,
      328,  161,  118,  118,  118,  328,  328,  164,  328,  328,
      118,  165,   68,   68,   68,   68,   68,   68,   68,   68,
       68,  328,   68,   68,   68,   68,   68,   68,   68,   68,
       68,  328,  328,   68,   68,   68,   68,   68,   68,   68,
       68,   68,  328,  328,  166,  168,  171,  328,  328,  169,

      328,  328,  170,  167,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  173,   68,   68,   68,
       68,   68,   68,  328,  172,  175,   68,   68,   68,  328,
      328,  174,   68,   68,   68,   68,   68,   68,   68,   68,
       68,  328,  328,  176,  328,  328,  177,   68,   68,   68,
      328,  179,   68,   68,   68,  178,   68,   68,   68,   68,
       68,   68,   68,   68,   68,  180,  328,  328,  182,  328,
      181,   68,   68,   68,   68,   68,   68,   68,   68,   68,
      328,   68,   68,   68,  328,  187,  328,  183,  328,  185,
      328,  184,   68,   68,   68,  328,  328,  186,   68,   68,

       68,  328,  328,  188,  190,  189,   68,   68,   68,   68,
       68,   68,  192,   68,   68,   68,  191,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  328,  194,   68,   68,
       68,  328,  328,  196,  328,  328,  193,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  328,  198,   68,   68,
       68,  328,  195,  197,   68,   68,   68,   68,   68,   68,
      328,  201,  328,  199,  328,  202,   68,   68,   68,   68,
       68,   68,  203,  200,   68,   68,   68,   68,   68,   68,
       68,   68,   68,  328,   68,   68,   68,   68,   68,   68,
       68,   68,   68,  328,  204,  207,   68,   68,   68,   68,

       68,   68,  328,  328,  205,   68,   68,   68,  328,  206,
       68,   68,   68,   68,   68,   68,  328,  328,  208,  328,
      328,  210,   68,   68,   68,  328,  328,  209,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,  211,   68,   68,   68,  328,  213,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,  328,  212,  214,  328,  328,  215,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  328,  328,  216,   68,
       68,   68,   68,   68,   68,  218,   68,   68,   68,  217,
      219,   68,   68,   68,   68,   68,   68,   68,   68,   68,

      328,  328,  222,   68,   68,   68,   68,   68,   68,  328,
      328,  221,  220,   68,   68,   68,  328,  328,  224,   68,
       68,   68,  328,  328,  223,  328,  328,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  328,  225,  226,  227,
       68,   68,   68,   68,   68,   68,  328,  328,  228,   68,
       68,   68,   68,   68,   68,  328,  328,  229,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
      328,  230,   68,   68,   68,  328,  232,  328,  328,  233,
       68,   68,   68,   68,   68,   68,  328,  328,  231,   68,
       68,   68,   68,   68,   68,  234,   68,   68,   68,  328,

      236,   68,   68,   68,   68,   68,   68,   68,   68,   68,
      328,  235,  328,  328,  240,  328,  239,   68,   68,   68,
      237,  238,   68,   68,   68,   68,   68,   68,   68,   68,
       68,  328,  328,  241,   68,   68,   68,  328,  328,  244,
       68,   68,   68,  328,  328,  242,   68,   68,   68,  243,
      328,  245,   68,   68,   68,  328,  328,  246,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
      247,  328,  328,  249,   68,   68,   68,  248,  250,   68,
       68,   68,   68,   68,   68,  328,  252,  328,  328,  251,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,  328,  328,  254,   68,   68,   68,  328,  328,
      253,   68,   68,   68,  328,  255,   68,   68,   68,   68,
       68,   68,  328,  328,  256,  259,  328,  328,  258,  328,
      257,   68,   68,   68,  260,   68,   68,   68,  328,   68,
       68,   68,   68,   68,   68,   68,   68,   68,  261,   68,
       68,   68,   68,   68,   68,  328,  264,   68,   68,   68,
       68,   68,   68,  262,  263,   68,   68,   68,  328,   68,
       68,   68,   68,   68,   68,  328,   68,   68,   68,  267,
      328,  266,  328,  265,   68,   68,   68,   68,   68,   68,
      269,  328,  328,  268,  270,  271,   68,   68,   68,   68,

       68,   68,  328,   68,   68,   68,   68,   68,   68,  272,
       68,   68,   68,   68,   68,   68,  273,   68,   68,   68,
      328,  274,   68,   68,   68,  328,  328,  275,  276,   68,
       68,   68,  277,  328,  278,   68,   68,   68,   68,   68,
       68,   68,   68,   68,  279,  328,  328,  280,  328,  328,
      281,   68,   68,   68,   68,   68,   68,  328,   68,   68,
       68,   68,   68,   68,  328,  282,   68,   68,   68,   68,
       68,   68,   68,   68,   68,  328,  286,   68,   68,   68,
      288,   68,   68,   68,  283,   68,   68,   68,  328,  328,
      284,  285,  290,   68,   68,   68,  328,  287,   68,   68,

       68,   68,   68,   68,  289,  328,  291,   68,   68,   68,
      328,  328,  293,  328,  292,   68,   68,   68,   68,   68,
       68,   68,   68,   68,  328,  328,  294,   68,   68,   68,
      328,  295,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,  328,  328,  297,
      298,   68,   68,   68,  328,  328,  296,  328,  328,  300,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,  328,  328,  299,  328,  301,  303,   68,   68,
       68,  305,   68,   68,   68,   68,   68,   68,  328,  328,
      302,   68,   68,   68,  304,  306,  328,   68,   68,   68,

       68,   68,   68,   68,   68,   68,  328,   68,   68,   68,
       68,   68,   68,  328,  328,  307,  308,  311,   68,   68,
       68,   68,   68,   68,  312,  309,   68,   68,   68,  310,
       68,   68,   68,   68,   68,   68,   68,   68,   68,  328,
      328,  313,   68,   68,   68,  328,  314,  316,   68,   68,
       68,   68,   68,   68,   68,   68,   68,  328,  328,  315,
      328,  318,  328,  328,  317,   68,   68,   68,  319,   68,
       68,   68,  320,  328,  328,  321,   68,   68,   68,  322,
       68,   68,   68,   68,   68,   68,   68,   68,   68,  328,
      328,  323,   68,   68,   68,  328,   68,   68,   68,   68,

       68,   68,  324,   68,   68,   68,   68,   68,   68,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  325,
      326,  328,  328,  327,   52,  328,   52,  117,  328,  117,
        3,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328
    } ;

static const flex_int16_t yy_chk[1487] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   14,   16,   17,   17,   17,
       25,   25,   25,  332,   16,   14,   19,  330,   19,   19,
       19,   20,  165,   20,   20,   20,   28,   28,   28,   29,
       29,   29,   30,   30,   30,   45,   45,   45,   28,   28,
       31,   31,   31,   33,   33,   33,   52,   28,   29,   49,

       28,   24,   23,   30,   29,   28,   28,   30,   32,   32,
       32,   45,   31,   22,   33,   34,   34,   34,   18,   32,
       35,   35,   35,   10,   31,   36,   36,   36,    8,   32,
       32,   34,    7,   32,   37,   37,   37,    3,    0,   34,
        0,   35,   38,   38,   38,    0,   36,    0,    0,   37,
       39,   39,   39,    0,    0,   37,   40,   40,   40,    0,
        0,   38,   41,   41,   41,   39,    0,   38,   42,   42,
       42,    0,   43,   43,   43,    0,   46,   46,   46,   42,
       40,   41,    0,   42,   59,   59,   59,   42,    0,    0,
       41,   43,    0,   43,   44,   44,   44,   46,   43,   43,

        0,    0,   43,    0,    0,   44,   47,   47,   47,   44,
       60,   60,   60,   69,   69,   69,    0,   62,    0,   44,
        0,    0,   44,   62,   62,   62,   63,   47,   63,   63,
       63,   62,   64,    0,   64,   64,   64,   70,   70,   70,
       71,   71,   71,   72,   72,   72,    0,    0,   73,   73,
       73,   74,   74,   74,   76,   76,   76,    0,   72,    0,
       75,   75,   75,    0,    0,   71,   70,   73,    0,    0,
       74,   75,   77,   77,   77,   78,   78,   78,   79,   79,
       79,    0,   76,   80,   80,   80,   81,   81,   81,    0,
       78,   83,   83,   83,    0,   84,   84,   84,   85,   85,

       85,   77,   86,   86,   86,   81,   87,   87,   87,   79,
       84,   79,   80,   83,   88,   88,   88,   89,   89,   89,
        0,   87,    0,   85,   90,   90,   90,   91,   91,   91,
       86,    0,   92,   92,   92,    0,   89,    0,    0,   90,
        0,    0,   91,   93,   93,   93,    0,   89,   92,   94,
       94,   94,   95,   95,   95,   96,   96,   96,   93,   97,
       97,   97,    0,   94,    0,    0,   96,   98,   98,   98,
       99,   99,   99,  100,  100,  100,    0,  101,  101,  101,
      103,  103,  103,   95,    0,  102,  102,  102,    0,   99,
      101,  104,  104,  104,  105,  105,  105,  100,  106,  106,

      106,   98,  102,    0,  103,  105,  104,  107,  107,  107,
      108,  108,  108,  109,  109,  109,    0,  110,  110,  110,
      111,  111,  111,  116,  116,  116,  106,  112,  112,  112,
      113,  113,  113,    0,  108,  107,    0,    0,  112,  111,
        0,  109,  114,  114,  114,  113,  118,  109,  110,    0,
        0,  111,  118,  118,  118,    0,    0,  114,    0,    0,
      118,  118,  119,  119,  119,  120,  120,  120,  121,  121,
      121,    0,  122,  122,  122,  123,  123,  123,  124,  124,
      124,    0,    0,  125,  125,  125,  126,  126,  126,  127,
      127,  127,    0,    0,  120,  122,  125,    0,    0,  123,

        0,    0,  124,  121,  128,  128,  128,  129,  129,  129,
      130,  130,  130,  131,  131,  131,  128,  132,  132,  132,
      133,  133,  133,    0,  127,  130,  134,  134,  134,    0,
        0,  129,  135,  135,  135,  136,  136,  136,  137,  137,
      137,    0,    0,  131,    0,    0,  132,  138,  138,  138,
        0,  134,  139,  139,  139,  133,  140,  140,  140,  141,
      141,  141,  142,  142,  142,  135,    0,    0,  137,    0,
      136,  143,  143,  143,  144,  144,  144,  145,  145,  145,
        0,  146,  146,  146,    0,  143,    0,  139,    0,  141,
        0,  140,  147,  147,  147,    0,    0,  142,  148,  148,

      148,    0,    0,  144,  146,  145,  149,  149,  149,  150,
      150,  150,  148,  151,  151,  151,  147,  152,  152,  152,
      153,  153,  153,  154,  154,  154,    0,  150,  155,  155,
      155,    0,    0,  153,    0,    0,  149,  156,  156,  156,
      157,  157,  157,  158,  158,  158,    0,  155,  159,  159,
      159,    0,  152,  154,  160,  160,  160,  161,  161,  161,
        0,  159,    0,  157,    0,  160,  162,  162,  162,  163,
      163,  163,  161,  158,  164,  164,  164,  166,  166,  166,
      167,  167,  167,    0,  168,  168,  168,  169,  169,  169,
      170,  170,  170,    0,  162,  168,  171,  171,  171,  172,

      172,  172,    0,    0,  163,  173,  173,  173,    0,  164,
      174,  174,  174,  175,  175,  175,    0,    0,  171,    0,
        0,  174,  176,  176,  176,    0,    0,  173,  177,  177,
      177,  178,  178,  178,  179,  179,  179,  180,  180,  180,
      181,  181,  181,  177,  182,  182,  182,    0,  180,  183,
      183,  183,  184,  184,  184,  185,  185,  185,  186,  186,
      186,    0,  179,  182,    0,    0,  185,  187,  187,  187,
      188,  188,  188,  189,  189,  189,    0,    0,  185,  190,
      190,  190,  191,  191,  191,  188,  192,  192,  192,  187,
      190,  193,  193,  193,  194,  194,  194,  195,  195,  195,

        0,    0,  193,  196,  196,  196,  197,  197,  197,    0,
        0,  192,  191,  198,  198,  198,    0,    0,  196,  199,
      199,  199,    0,    0,  194,    0,    0,  200,  200,  200,
      201,  201,  201,  202,  202,  202,    0,  198,  199,  200,
      203,  203,  203,  204,  204,  204,    0,    0,  201,  205,
      205,  205,  206,  206,  206,    0,    0,  202,  207,  207,
      207,  208,  208,  208,  209,  209,  209,  210,  210,  210,
        0,  204,  211,  211,  211,    0,  208,    0,    0,  209,
      212,  212,  212,  213,  213,  213,    0,    0,  207,  214,
      214,  214,  215,  215,  215,  210,  216,  216,  216,    0,

      214,  217,  217,  217,  218,  218,  218,  219,  219,  219,
        0,  213,    0,    0,  218,    0,  217,  220,  220,  220,
      215,  216,  221,  221,  221,  222,  222,  222,  223,  223,
      223,    0,    0,  219,  224,  224,  224,    0,    0,  223,
      225,  225,  225,    0,    0,  221,  226,  226,  226,  222,
        0,  223,  227,  227,  227,    0,    0,  225,  228,  228,
      228,  229,  229,  229,  230,  230,  230,  231,  231,  231,
      226,    0,    0,  228,  232,  232,  232,  227,  229,  233,
      233,  233,  234,  234,  234,    0,  231,    0,    0,  230,
      235,  235,  235,  236,  236,  236,  237,  237,  237,  238,

      238,  238,    0,    0,  235,  239,  239,  239,    0,    0,
      234,  240,  240,  240,    0,  236,  241,  241,  241,  242,
      242,  242,    0,    0,  237,  240,    0,    0,  239,    0,
      238,  243,  243,  243,  240,  244,  244,  244,    0,  245,
      245,  245,  246,  246,  246,  247,  247,  247,  243,  248,
      248,  248,  249,  249,  249,    0,  247,  250,  250,  250,
      251,  251,  251,  244,  245,  252,  252,  252,    0,  253,
      253,  253,  254,  254,  254,    0,  255,  255,  255,  250,
        0,  249,    0,  248,  256,  256,  256,  257,  257,  257,
      252,    0,    0,  251,  253,  255,  258,  258,  258,  259,

      259,  259,    0,  260,  260,  260,  262,  262,  262,  256,
      261,  261,  261,  263,  263,  263,  257,  264,  264,  264,
        0,  258,  265,  265,  265,    0,    0,  259,  260,  266,
      266,  266,  261,    0,  262,  267,  267,  267,  268,  268,
      268,  269,  269,  269,  263,    0,    0,  264,    0,    0,
      267,  270,  270,  270,  271,  271,  271,    0,  272,  272,
      272,  273,  273,  273,    0,  269,  274,  274,  274,  275,
      275,  275,  276,  276,  276,    0,  273,  277,  277,  277,
      275,  278,  278,  278,  270,  279,  279,  279,    0,    0,
      271,  272,  277,  280,  280,  280,    0,  274,  281,  281,

      281,  282,  282,  282,  276,    0,  278,  283,  283,  283,
        0,    0,  280,    0,  279,  284,  284,  284,  285,  285,
      285,  286,  286,  286,    0,    0,  284,  287,  287,  287,
        0,  286,  288,  288,  288,  289,  289,  289,  290,  290,
      290,  291,  291,  291,  292,  292,  292,    0,    0,  288,
      289,  293,  293,  293,    0,    0,  287,    0,    0,  292,
      294,  294,  294,  295,  295,  295,  296,  296,  296,  297,
      297,  297,    0,    0,  291,    0,  293,  295,  298,  298,
      298,  296,  299,  299,  299,  300,  300,  300,    0,    0,
      294,  301,  301,  301,  295,  300,    0,  302,  302,  302,

      303,  303,  303,  304,  304,  304,    0,  305,  305,  305,
      306,  306,  306,    0,    0,  301,  302,  305,  307,  307,
      307,  308,  308,  308,  306,  303,  309,  309,  309,  304,
      310,  310,  310,  311,  311,  311,  312,  312,  312,    0,
        0,  306,  313,  313,  313,    0,  308,  311,  314,  314,
      314,  315,  315,  315,  316,  316,  316,    0,    0,  309,
        0,  312,    0,    0,  311,  317,  317,  317,  313,  318,
      318,  318,  314,    0,    0,  315,  319,  319,  319,  316,
      320,  320,  320,  321,  321,  321,  322,  322,  322,    0,
        0,  317,  323,  323,  323,    0,  324,  324,  324,  325,

      325,  325,  318,  326,  326,  326,  327,  327,  327,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  322,
      324,    0,    0,  325,  329,    0,  329,  331,    0,  331,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gpl.l"
#line 2 "gpl.l"

#include "error.h"
#include "parser.h" // replacement for y.tab.h

#include <ctype.h>
#include <iostream>
using namespace std;


int line_count = 1;          // used to keep track of the input line

extern Error error_handler;  // error reporting object

/* count line feeds */
void count_lines(char *str)
{
  while(*str)
  {
    if (*str++ == '\n')
    {
        line_count ++;
    }
  }
}

void discard()
{
  count_lines(yytext);
}

/* the following functions are "called" when a token is found */

int emit(int token)
{
  count_lines(yytext);
  return(token);
}

int emit_with_line_number(int token)
{
  yylval.union_int = line_count;
  return emit(token);
}

int emit_str_constant(int token)
{
  yytext[strlen(yytext)-1] = 0;
  yylval.union_string = new string(yytext + 1);
  return emit(token);
}

int emit_id(int token)
{
  yylval.union_string = new string(yytext);
  return emit(token);
}

int emit_int(int token)
{
  yylval.union_int = atoi(yytext);
  return emit(token);
}

int emit_double(int token)
{
  yylval.union_double = atof(yytext);
  return emit(token);
}

int emit_error(int token)
{
  error_handler.error(Error::ILLEGAL_TOKEN,yytext);
  yylval.union_string = new string(yytext);
  return emit(token);
}

int j;

#line 956 "lex.yy.c"
#line 957 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 82 "gpl.l"


#line 1177 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1431 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "gpl.l"
discard();
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 85 "gpl.l"
discard();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 87 "gpl.l"
return emit(T_INT);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 88 "gpl.l"
return emit(T_DOUBLE);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 89 "gpl.l"
return emit(T_STRING);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "gpl.l"
return emit(T_TRIANGLE);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "gpl.l"
return emit(T_PIXMAP);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "gpl.l"
return emit(T_CIRCLE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "gpl.l"
return emit(T_RECTANGLE);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "gpl.l"
return emit(T_TEXTBOX);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "gpl.l"
return emit_with_line_number(T_FORWARD);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "gpl.l"
return emit(T_INITIALIZATION);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "gpl.l"
return emit(T_TERMINATION);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "gpl.l"
return emit(T_ON);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "gpl.l"
return emit(T_ANIMATION);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "gpl.l"
return emit(T_IF);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "gpl.l"
return emit(T_FOR);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "gpl.l"
return emit(T_ELSE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "gpl.l"
return emit_with_line_number(T_EXIT);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "gpl.l"
return emit_with_line_number(T_PRINT);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "gpl.l"
return emit(T_TRUE);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "gpl.l"
return emit(T_FALSE);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "gpl.l"
return emit(T_SPACE);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "gpl.l"
return emit(T_LEFTARROW);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "gpl.l"
return emit(T_RIGHTARROW);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "gpl.l"
return emit(T_UPARROW);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "gpl.l"
return emit(T_DOWNARROW);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 114 "gpl.l"
return emit(T_LEFTMOUSE_DOWN);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 115 "gpl.l"
return emit(T_MIDDLEMOUSE_DOWN);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 116 "gpl.l"
return emit(T_RIGHTMOUSE_DOWN);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 117 "gpl.l"
return emit(T_LEFTMOUSE_UP);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "gpl.l"
return emit(T_MIDDLEMOUSE_UP);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 119 "gpl.l"
return emit(T_RIGHTMOUSE_UP);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 "gpl.l"
return emit(T_MOUSE_MOVE);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 "gpl.l"
return emit(T_MOUSE_DRAG);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 "gpl.l"
return emit(T_F1);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 "gpl.l"
return emit(T_AKEY);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 124 "gpl.l"
return emit(T_SKEY);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "gpl.l"
return emit(T_DKEY);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "gpl.l"
return emit(T_FKEY);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "gpl.l"
return emit(T_HKEY);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 128 "gpl.l"
return emit(T_JKEY);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 129 "gpl.l"
return emit(T_KKEY);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 130 "gpl.l"
return emit(T_LKEY);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 131 "gpl.l"
return emit(T_WKEY);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 132 "gpl.l"
return emit(T_ZKEY);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 134 "gpl.l"
return emit(T_LPAREN);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 135 "gpl.l"
return emit(T_RPAREN);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 136 "gpl.l"
return emit(T_LBRACE);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 137 "gpl.l"
return emit(T_RBRACE);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 138 "gpl.l"
return emit(T_LBRACKET);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 139 "gpl.l"
return emit(T_RBRACKET);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 140 "gpl.l"
return emit(T_SEMIC);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 141 "gpl.l"
return emit(T_COMMA);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 142 "gpl.l"
return emit(T_PERIOD);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 144 "gpl.l"
return emit(T_ASSIGN);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 145 "gpl.l"
return emit(T_PLUS_ASSIGN);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 146 "gpl.l"
return emit(T_MINUS_ASSIGN);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 147 "gpl.l"
return emit(T_PLUS_PLUS);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 148 "gpl.l"
return emit(T_MINUS_MINUS);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 150 "gpl.l"
return emit(T_SIN);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 151 "gpl.l"
return emit(T_COS);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 152 "gpl.l"
return emit(T_TAN);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 153 "gpl.l"
return emit(T_ASIN);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 154 "gpl.l"
return emit(T_ACOS);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 155 "gpl.l"
return emit(T_ATAN);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 156 "gpl.l"
return emit(T_SQRT);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 157 "gpl.l"
return emit(T_ABS);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 158 "gpl.l"
return emit(T_FLOOR);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 159 "gpl.l"
return emit(T_RANDOM);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 161 "gpl.l"
return emit(T_TOUCHES);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 162 "gpl.l"
return emit(T_NEAR);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 164 "gpl.l"
return emit(T_MULTIPLY);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 165 "gpl.l"
return emit(T_DIVIDE);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 166 "gpl.l"
return emit(T_PLUS);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 167 "gpl.l"
return emit(T_MINUS);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 168 "gpl.l"
return emit(T_MOD);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 170 "gpl.l"
return emit(T_LESS);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 171 "gpl.l"
return emit(T_GREATER);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 172 "gpl.l"
return emit(T_LESS_EQUAL);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 173 "gpl.l"
return emit(T_GREATER_EQUAL);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 174 "gpl.l"
return emit(T_EQUAL);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 175 "gpl.l"
return emit(T_NOT_EQUAL);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 176 "gpl.l"
return emit(T_NOT);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 177 "gpl.l"
return emit(T_AND);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 178 "gpl.l"
return emit(T_OR);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 181 "gpl.l"
return emit_double(T_DOUBLE_CONSTANT);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 182 "gpl.l"
return emit_double(T_DOUBLE_CONSTANT);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 183 "gpl.l"
return emit_double(T_DOUBLE_CONSTANT);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 184 "gpl.l"
return emit_int(T_INT_CONSTANT);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 185 "gpl.l"
return emit_str_constant(T_STRING_CONSTANT);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 186 "gpl.l"
return emit_id(T_ID);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 188 "gpl.l"
return emit_error(T_ERROR);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 189 "gpl.l"
ECHO;
	YY_BREAK
#line 1705 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 328);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 189 "gpl.l"

